#!/bin/sh

DATABASE="chinook"
DATABASE_USER="chinook"
DATABASE_PASSWORD="password"

cat <<EOSQL
CREATE DATABASE IF NOT EXISTS $DATABASE;
CREATE USER IF NOT EXISTS '$DATABASE_USER'@'localhost' IDENTIFIED BY '$DATABASE_PASSWORD';
GRANT ALL PRIVILEGES ON $DATABASE.* to '$DATABASE_USER'@'localhost' WITH GRANT OPTION;
USE $DATABASE;
SET GLOBAL log_bin_trust_function_creators = 1;
SOURCE data/chinook.sql;
EOSQL

