#!/bin/sh

DATABASE="chinook"
DATABASE_USER="chinook"
DATABASE_PASSWORD="password"

cat <<EOSQL
CREATE DATABASE IF NOT EXISTS $DATABASE;
CREATE USER IF NOT EXISTS '$DATABASE_USER'@'localhost' IDENTIFIED BY '$DATABASE_PASSWORD';
GRANT ALL PRIVILEGES ON $DATABASE.* to '$DATABASE_USER'@'localhost';
USE $DATABASE;
SOURCE data/chinook.sql;
EOSQL

